// GENERATED by the Offer Mirror full-ladder prompt (docs/handoff/offers/).
// Phase G output (outside-in perception via answer engines, 2026-07-25). Never hand-edit.

import type { PerceptionData } from './types'

export const perception: PerceptionData = {
  queriedAt: '2026-07-25',
  records: [
    {
      id: 'P-01',
      source: 'chat_gpt/gpt-5.5 (web)',
      query: 'What does the company Sale Solution (salesolution.net) do?',
      saysWeDo: 'Small digital growth/marketing/sales-automation company; builds \'revenue engines\' not a traditional agency; four focus areas: industrial distributors, home services (roofing/HVAC/plumbing/electrical), dental + medical aesthetics, consumer/DTC; founder-led by Artur Shepel; no ad markup, no lock-in, client owns code/data/lists.',
      errors: [
        'Cited homepage title is stale: \'Digital Marketing & Sales: SEO Expert Guides and Services · Sale Solution\'',
      ],
      omissions: [
        'No pricing, no guarantee, no probe/instruments, no learning hub',
      ],
      quotes: [
        'builds "revenue engines" for businesses rather than as a traditional ad agency',
        'stated focus areas include industrial distributors, home services… dental and medical aesthetics… consumer/DTC brands',
      ],
    },
    {
      id: 'P-02',
      source: 'claude/claude-sonnet-4-6 (web)',
      query: 'What does the company Sale Solution (salesolution.net) do?',
      saysWeDo: 'Full-service digital marketing and growth agency; \'external Chief Revenue Officer\'; e-commerce solutions, SEO & content, conversion optimization, B2B platform optimization (Thomasnet, GlobalSpec), on-site experience optimization; located Sunny Isles Beach.',
      errors: [
        'Pre-pivot agency story sourced from Crunchbase/ZoomInfo, not the current site',
        'Old address (Sunny Isles Beach)',
        '\'external CRO\' framing exists nowhere in current copy',
        'Old homepage service list (Thomasnet/GlobalSpec platform optimization)',
      ],
      omissions: [
        'No Revenue Engine, no verticals, no AI-search/GEO focus, no one-operator positioning',
      ],
      quotes: [
        'They act as an external Chief Revenue Officer for their clients',
        'B2B & Technical Platform Optimization… Thomasnet, GlobalSpec, and industry-specific directories',
      ],
    },
    {
      id: 'P-03',
      source: 'gemini/gemini-3.5-flash (web)',
      query: 'What does the company Sale Solution (salesolution.net) do?',
      saysWeDo: 'Boutique one-operator B2B consultancy (IT Sale Solution LLC, FL); builds the \'Revenue Engine\'; AIO/GEO for AI tools; catalog restructuring for distributors; revenue-leak auditing + AI receptionists + follow-up automation; growth calls/leak audits as doors; industrial, home services, medical/dental niches.',
      errors: [
        'Omits the consumer/DTC vertical',
      ],
      omissions: [
        'No pricing, no guarantee split',
      ],
      quotes: [
        'operates as a boutique, "one-operator" consultancy led by its founder and CEO, Artur Shepel',
        'implement technical fixes, like AI receptionists and automated customer follow-up sequences',
      ],
    },
    {
      id: 'P-04',
      source: 'perplexity/sonar-pro (web)',
      query: 'What does the company Sale Solution (salesolution.net) do?',
      saysWeDo: 'Revenue-growth agency for e-commerce brands $2–15M; installs a \'Revenue Flywheel\' with four cylinders Conversion/Traffic/Ads/Retention; claims clients generated ~$40M additional revenue. — Note: Also burned a paragraph disambiguating from salesolution.ai / salessolutionsinc.net / salesolution.ch — name-collision noise is real.',
      errors: [
        '\'Revenue Flywheel\', \'Conversion/Traffic/Ads/Retention\', \'$2–15M\', \'~$40M generated\' — none exist in the current repo; sourced from a cached/old /book-growth-call/ page',
        'Audience narrowed to e-commerce DTC only',
      ],
      omissions: [
        'All four current verticals, the real Revenue Engine architecture, the operator positioning',
      ],
      quotes: [
        'installs and manages a complete, integrated "revenue flywheel" system',
        'clients using this system have generated around $40 million in additional revenue',
      ],
    },
    {
      id: 'P-05',
      source: 'chat_gpt/gpt-5.5 (web)',
      query: 'Who is salesolution.net for, and what exactly do they sell?',
      saysWeDo: 'For businesses selling products/services/jobs/appointments; four verticals as chips; sells a managed \'revenue engine\' service: get found (AI-search/SEO), convert (response, quotes, booking), retain (win-back, reviews, reorder); promise \'Get found. Win the sale. Keep them coming back.\'',
      errors: [
        'Same stale homepage title cited',
      ],
      omissions: [
        'Price silent; guarantee absent',
      ],
      quotes: [
        'What they sell is not a single software product; it\'s a managed "revenue engine" service',
        'losing revenue because they are not visible enough, not responding/following up fast enough, or not reselling',
      ],
    },
    {
      id: 'P-06',
      source: 'perplexity/sonar-pro (web)',
      query: 'Who is salesolution.net for, and what exactly do they sell?',
      saysWeDo: 'Consumer/DTC brands $2–15M; installed+managed growth system; correctly quotes NEW consumer page ($30K install scaled to stake, cylinders $4–15K/mo added as they pay for themselves) but wraps it in OLD flywheel framing (foundation+performance model, weekly strategy calls, dedicated Slack).',
      errors: [
        'Blends cached old /book-growth-call/ copy with the live consumer-brands page',
        'Presents the DTC vertical as the whole business',
      ],
      omissions: [
        'Industrial, trades, dental motions entirely absent',
      ],
      quotes: [
        'Implementation from about $30,000, scaled to the size of what\'s at stake',
        'turns struggling $2–15M e-commerce brands into predictable growth machines',
      ],
    },
    {
      id: 'P-07',
      source: 'chat_gpt/gpt-5.5 (web)',
      query: 'Is Sale Solution (salesolution.net) a legit agency? What does working with them cost?',
      saysWeDo: 'Likely legit small consultancy; cost story taken from CLUTCH: minimum project $1,000+, avg $100–149/hr, most reviewed projects under $10,000; 5 reviews, 5.0; \'could not confirm exact package prices\' despite site\'s published-prices claim; old Sunny Isles address. — Note: Clutch is the de-facto pricing page in the eyes of answer engines.',
      errors: [
        'Third-party price anchor (sub-$10K projects) contradicts the $30K-install positioning',
        'Old address',
      ],
      omissions: [
        'No install-first model, no Catalog AI per-SKU pricing surfaced',
      ],
      quotes: [
        'minimum project size: $1,000+, average hourly rate: $100–$149/hr',
        'most common reviewed project size is under $10,000',
      ],
    },
    {
      id: 'P-08',
      source: 'chat_gpt/gpt-5.5 (web)',
      query: 'How do I get my distributor site cited in Google AI Overviews for part numbers? Any specialists?',
      saysWeDo: 'FIRM ABSENT. Generic best-practice (Product schema, MPN pages, Merchant Center, crawl hygiene) + advice to hire \'a technical ecommerce SEO specialist with B2B distributor experience, not a generic AI SEO person\'; explicit skepticism of AIO-citation promises.',
      errors: [],
      omissions: [
        'Sale Solution not mentioned despite this being its flagship pitch',
      ],
      quotes: [
        'Be skeptical of anyone promising "we\'ll get you cited in Google AI Overviews."',
        'hire a technical ecommerce SEO specialist with B2B distributor experience, not a generic "AI SEO" person',
      ],
    },
    {
      id: 'P-09',
      source: 'perplexity/sonar-pro (web)',
      query: 'Best agency to make an industrial parts catalog show up in AI search',
      saysWeDo: 'FIRM ABSENT. LattSEO (\'Industrial Catalog SEO… AI search visibility: ChatGPT, Perplexity, Gemini, AI Overviews, Copilot\') and First Page Sage (industrial GEO) own the answer; Hedges & Co for truck parts. — Note: LattSEO\'s service page is nearly a Catalog AI clone — the pitch works, someone else is being cited for it.',
      errors: [],
      omissions: [
        'Sale Solution absent from its most-owned category',
      ],
      quotes: [
        'every commercially valuable page in your catalog findable on Google and in AI search engines (LattSEO)',
        'pioneering generative engine optimization… rank not only in Google but also in ChatGPT (First Page Sage)',
      ],
    },
    {
      id: 'P-10',
      source: 'gemini/gemini-3.5-flash (web)',
      query: 'Service that answers missed calls and chases cold quotes for roofing companies — done-for-you?',
      saysWeDo: 'FIRM ABSENT. RoofReply (managed missed-call text-back), MustHavesAI (AI answering + estimate follow-up), PointWake/Contractor OS (GHL builds), MapleConnect (AI-native CRM), ProLine, Clara AI, SkipCalls own the category.',
      errors: [],
      omissions: [
        'Sale Solution absent from the exact Answer & Book + Recover pitch',
      ],
      quotes: [
        'RoofReply texts the homeowner in seconds',
        'Estimate Follow-Up… systematically nudge outstanding, cold quotes until they close or opt out (MustHavesAI)',
      ],
    },
    {
      id: 'P-11',
      source: 'chat_gpt/gpt-5.5 (web)',
      query: 'System to recover unscheduled treatment plans and overdue recall for a dental practice — done-for-you?',
      saysWeDo: 'FIRM ABSENT. Full Schedule, Dental Booking Agency, Xcare, 10x Dental, DentRecall, SmilePing, Operaitor, Kluse own the category; buyer checklist includes PMS integration, HIPAA/BAA, completed-production reporting — the dentists page\'s exact claims, attributed to others.',
      errors: [],
      omissions: [
        'Sale Solution absent from the dental recall/treatment-plan category',
      ],
      quotes: [
        'Full Schedule — dental recall and follow-up support using dental-experienced staff working inside your PMS',
        'report completed production, not just patients contacted',
      ],
    },
    {
      id: 'P-12',
      source: 'claude/claude-sonnet-4-6 (web)',
      query: 'How do showroom retailers (jewelry, furniture, flooring) stop losing sales to online stores? Who helps?',
      saysWeDo: 'FIRM ABSENT. Generic anti-showrooming strategies + vendor table (Zolak, Roomvo, Shopify POS, Placer.ai, Wiser…); no growth-system operator named at all.',
      errors: [],
      omissions: [
        'Sale Solution absent; no one owns this category — open lane',
      ],
      quotes: [
        'customers browse in-store but buy online at a lower price',
        'use their physical presence as a trust and experience advantage',
      ],
    },
    {
      id: 'P-13',
      source: 'dfs ai_opt_llm_ment_search (chat_gpt platform)',
      query: 'mentions: domain salesolution.net + keyword \'Sale Solution\'',
      saysWeDo: 'ZERO items — the domain and brand appear nowhere in the tracked LLM-mentions dataset.',
      errors: [],
      omissions: [
        'No LLM-answer presence at dataset scale',
      ],
      quotes: [
        'items: []',
      ],
    },
    {
      id: 'P-14',
      source: 'dfs ai_opt_llm_ment_top_pages',
      query: 'top cited pages for salesolution.net',
      saysWeDo: 'ZERO items — no pages from the domain are cited in tracked LLM answers.',
      errors: [],
      omissions: [],
      quotes: [
        'items: []',
      ],
    },
    {
      id: 'P-15',
      source: 'ChatGPT live scraper',
      query: 'what does salesolution.net do',
      saysWeDo: 'Accurate current description: unified revenue engine, GEO/AI search, SEO/content, paid, website optimization, lead management (calls/booking/quotes/reactivation), retention; four verticals; operator Artur Shepel; IT Sale Solution LLC, North Miami Beach.',
      errors: [
        'Homepage source title stale (\'Digital Marketing & Sales: SEO Expert Guides and Services\')',
      ],
      omissions: [
        'Pricing, guarantee, instruments',
      ],
      quotes: [
        'positions itself as providing a unified "revenue engine" rather than offering isolated marketing services',
        'operated by Artur Shepel, who presents himself as the primary strategist and point of contact',
      ],
    },
    {
      id: 'P-16',
      source: 'ChatGPT live scraper',
      query: 'best GEO agency for industrial distributors',
      saysWeDo: 'FIRM ABSENT. Shortlist: RH Blake, First Page Sage, The ABM Agency, Directive, Siege Media, Omniscient Digital — sourced from agencies\' own listicles; \'$10M–$100M distributor: RH Blake or The ABM Agency\' (the exact ICP band).',
      errors: [],
      omissions: [
        'Sale Solution absent; the cited sources are competitor-authored roundups',
      ],
      quotes: [
        '$10M–$100M distributor: RH Blake or The ABM Agency',
        'Many GEO agencies still focus on SaaS. That experience doesn\'t always transfer well to industrial distribution.',
      ],
    },
    {
      id: 'P-17',
      source: 'Google SERP (live)',
      query: 'sale solution',
      saysWeDo: 'SITE ABSENT from page 1. Sales Solutions Inc (safety rep group) #1; rest = solution-selling definitions (Salesforce, Zendesk, Wikipedia, Highspot); AI Overview slot present (async).',
      errors: [
        'Brand term is a contested generic; the firm does not rank for its own name',
      ],
      omissions: [],
      quotes: [
        'Sales Solutions Inc - Home Of The Safety Market Experts (#1)',
      ],
    },
    {
      id: 'P-18',
      source: 'Google SERP (live)',
      query: 'salesolution.net',
      saysWeDo: '#1 with sitelinks Articles/Guides/Learning Hub/Glossary; title STALE (\'Digital Marketing & Sales: SEO Expert Guides and Services…\') while description is CURRENT (\'Win the customers you already pay for… named by AI\'); LinkedIn 10+ followers (\'go-to partner for revenue growth and customer loyalty\' — old copy); ZoomInfo; tomba.io scraped-email listing exposes a.***@salesolution.net under \'Chief Nursing Officer Email List\'.',
      errors: [
        'Live/indexed homepage title predates the repo\'s',
        'LinkedIn description pre-pivot',
        'Email-scraper listing pollutes the brand SERP',
      ],
      omissions: [],
      quotes: [
        'Digital Marketing & Sales: SEO Expert Guides and Services ...',
        'Win the customers you already pay for. We get industrial and local-service businesses named by AI',
      ],
    },
    {
      id: 'P-19',
      source: 'Google SERP (live)',
      query: 'sale solution revenue engine',
      saysWeDo: 'SITE ABSENT. AI Overview + dealhub.io glossary + revenue.io + generic \'AI revenue engine\' vendors (cetdigit, phoenixai.solutions, gorevenueengine.com, revenue.ai) own the phrase.',
      errors: [
        'The product name is a heavily contested generic; the firm doesn\'t rank for its own product term',
      ],
      omissions: [],
      quotes: [
        'What is a Revenue Engine? | DealHub AI (#1 organic)',
      ],
    },
  ],
  alignment: [
    {
      vertical: 'global',
      copySays: 'One operator, one Revenue Engine per business, four verticals, two doors; industrial book fully priced; machine layer still tells a two-motion six-service story.',
      canonSays: 'Same architecture minus published pricing (FD 2026-07-25); the two-motion axis is deliberate but stated nowhere public; canonical tagline signed but not deployed.',
      worldHears: 'Split by grounding: engines that read the live site describe the four-vertical engine business accurately; engines leaning on third parties serve the pre-pivot agency (Crunchbase \'external CRO\'), a flywheel-era cache ($2–15M, ~$40M), or a sub-$10K project shop (Clutch $1K min, $100–149/hr).',
      verdict: 'Identity fragmented by freshness, not comprehension — the current copy is machine-legible.',
      likelyCause: 'Old homepage title live in prod (DD-01), engine-side caches of the old call page (DD-04), and four stale third-party profiles that outrank the site\'s own story on trust/cost questions (P-02, P-07).',
    },
    {
      vertical: 'industrial',
      copySays: 'Be cited inside AI search, not just ranked underneath — six-service authority book, hydraulics proof, $30K+ installs.',
      canonSays: 'FD5: installed, future-proof system for e-commerce + business sales in the AI era; citations are mechanism. 12 cylinders, $2M/yr floor.',
      worldHears: 'Nothing. Absent from every industrial category answer; LattSEO (\'Industrial Catalog SEO… AI search visibility\') and First Page Sage own the pitch; GPT-5.5 tells buyers to be skeptical of anyone promising AI Overview citations and to hire \'a technical ecommerce SEO specialist, not a generic AI-SEO person.\'',
      verdict: 'The flagship category is owned by competitors quoting their own roundups; the citation-promise framing now attracts measured skepticism FD5 conveniently sidesteps.',
      likelyCause: 'Zero third-party citations (mentions dataset empty, P-13/P-14), DR-10, and no presence in the listicle surfaces engines actually cite (P-16).',
    },
    {
      vertical: 'home-services',
      copySays: 'The Revenue Engine for trades: answer every call, book the estimate, chase cold quotes, prove it.',
      canonSays: 'Same, with the day-90 guarantee retiring under FD3 in favor of enablement + KPI tracking.',
      worldHears: 'RoofReply, MustHavesAI, MapleConnect, ProLine, Clara AI, SkipCalls — the category answer is a mature vendor list; Sale Solution is absent.',
      verdict: 'The exact offer exists as a named category with incumbent answers; entering the answer set is content + directory work, not positioning work.',
      likelyCause: 'Empty educate/prove cells (F-24), no directory/roundup presence, campaign LP noindexed by design.',
    },
    {
      vertical: 'medical-dental',
      copySays: 'Recover presented treatment plans and overdue recall, HIPAA-aware, PMS write-back.',
      canonSays: 'Same; strongest guarantee language on the least-evidenced vertical (until FD3 lands).',
      worldHears: 'Full Schedule, Dental Booking Agency, Xcare, 10x Dental, DentRecall, SmilePing, Operaitor, Kluse — engines even recite the dentists page\'s own claims (PMS integration, completed-production reporting) attributed to competitors.',
      verdict: 'Category answers are crowded and specific; absence is total.',
      likelyCause: 'Zero dental proof or content; the one strong page (/revenue-engine/dentists/) has no citable satellite content.',
    },
    {
      vertical: 'consumer-dtc',
      copySays: 'The engine for showrooms: found first, answered in seconds, carts and quotes chased.',
      canonSays: 'Sell-product motion, growth-call door, no guarantee — deliberate.',
      worldHears: 'Nobody: the showrooming question returns generic strategy advice and tool vendors, no growth-system operator named at all.',
      verdict: 'OPEN LANE — the only vertical where the category answer has no incumbent operator; first credible citable content could own it.',
      likelyCause: 'No one has written the operator-shaped answer yet; the firm has one page and no content.',
    },
  ],
  fixList: [
    {
      rank: 1,
      fix: 'Refresh the four stale third-party profiles — Clutch (retire/annotate the $1K-min, sub-$10K, $100–149/hr bands), Crunchbase (\'external CRO\' blurb), ZoomInfo (Sunny Isles address), LinkedIn (\'go-to partner for revenue growth and customer loyalty\'). These are what engines quote on trust and cost questions, and they price-anchor the firm 30x below its floor.',
      seededBy: 'P-02, P-07, P-18',
    },
    {
      rank: 2,
      fix: 'Deploy the current homepage title (DD-01) and request recrawl of / and /book-growth-call/ — Perplexity still serves flywheel-era copy from cache; add sitemap lastmod discipline so freshness signals propagate.',
      seededBy: 'P-04, P-06, P-18, DD-01, DD-04',
    },
    {
      rank: 3,
      fix: 'Regenerate the machine layer from the live registry (D-11): llms.txt + Organization JSON-LD are byte-identical repo↔live and still teach every engine the two-motion, six-service story.',
      seededBy: 'P-01, P-05, DD-03, F-08',
    },
    {
      rank: 4,
      fix: 'Build the category-answer inventory: per-vertical educate content (the blog relaunch pack, docs/handoff/new-blog/) + placement in the roundup/listicle surfaces engines cite (agency shortlists, vendor directories, dental/trades software lists). Consumer-DTC first — it is the one open lane with no incumbent operator in the answer set.',
      seededBy: 'P-08…P-12, P-16, alignment rows 2–5',
    },
    {
      rank: 5,
      fix: 'Entity hardening for the name-collision field: consistent org profiles everywhere, alternateName kept for spelling variants only, and owned pages targeting \'Sale Solution\' + qualifier queries (reviews, pricing, about) — do not chase the naked generic term.',
      seededBy: 'P-04, P-17, P-19',
    },
    {
      rank: 6,
      fix: 'One attested win per vertical into Clutch/case studies as they land (Task 5.2) — the diligence surfaces engines quote must carry the install-class story, not 2025\'s sub-$10K projects.',
      seededBy: 'P-07, F-14',
    },
    {
      rank: 7,
      fix: 'Request removal of the tomba.io scraped-email listing (founder email pattern exposed under a \'Chief Nursing Officer Email List\') — brand-SERP pollution and a privacy-hygiene item.',
      seededBy: 'P-18',
    },
    {
      rank: 8,
      fix: 'Fix the proof-integrity duplicates before scaling any outreach (D-23) — an engine or buyer cross-reading the doubled metrics reads them as fabricated, and answer engines cross-read by default.',
      seededBy: 'P-05, F-01',
    },
  ],
  patterns: [
    'PATTERN-1 deploy/index staleness: live homepage title + cached call-page copy predate the repo; engines quote both.',
    'PATTERN-2 third-party drag: Crunchbase, ZoomInfo, LinkedIn, Clutch outrank the site\'s own story on trust/cost questions.',
    'PATTERN-3 category invisibility: absent from all five vertical buyer questions and both agency shortlists; LLM-mentions dataset empty.',
    'PATTERN-4 name collisions: the naked brand term and the product term are both owned by others; engines burn tokens disambiguating.',
    'PATTERN-5 grounded = accurate: engines reading the live site get the four-vertical engine story right — the gap is authority and freshness, not comprehension.',
  ],
}
