// GENERATED by the Offer Mirror full-ladder prompt (docs/handoff/offers/).
// Type contract for the three-stage offer dashboard: mirror (blind scan),
// drift (sighted vs canon), perception (outside-in). Data lives in the
// *.generated.ts siblings; refresh via the collector + a new prompt run.

// ---------------------------------------------------------------------------
// Stage 1 — Mirror (Phase B, frozen once serialized)
// ---------------------------------------------------------------------------

export type Confidence = 'H' | 'M' | 'L'

/** Verbatim copy evidence, ≤25 words, always with its source file. */
export interface EvidenceRef {
  file: string
  route?: string
  quote: string
}

/** One gradeable claim about what the copy says the business sells. */
export interface UClaim {
  id: string
  vertical: string
  element: string
  claim: string
  confidence: Confidence
  evidence: EvidenceRef[]
}

/** A vertical as evidenced by the copy itself — not the internal taxonomy. */
export interface VerticalBrief {
  key: string
  label: string
  summary: string
  claimIds: string[]
}

/** One record per scanned route (plus chrome + machine-layer records). */
export interface RouteRecord {
  route: string
  group: string
  sources: string[]
  pageType: string
  vertical: string
  offer: string
  promise: string
  priceSignals: string
  proof: string
  primaryCta: { label: string; href: string } | null
  voiceNotes: string
  quotes: EvidenceRef[]
  flags: string[]
}

export type FindingSeverity = 'P1' | 'P2' | 'P3' | 'P4'

export interface Finding {
  id: string
  severity: FindingSeverity
  kind: string
  title: string
  surfaces: { route: string; file: string }[]
  quotes: EvidenceRef[]
  whyItMatters: string
  direction: string
}

export type FunnelStage = 'attract' | 'educate' | 'prove' | 'convert'

export interface CoverageRow {
  vertical: string
  cells: Record<FunnelStage, string[]>
}

export interface OpenQuestion {
  scope: string
  question: string
}

export interface MirrorData {
  generatedAt: string
  method: string
  corpus: {
    routeCount: number
    fileCount: number
    sanityDocCount: number
    routes: string[]
    gaps: string[]
  }
  tldr: string
  claims: UClaim[]
  verticals: VerticalBrief[]
  inventory: RouteRecord[]
  coverage: CoverageRow[]
  findings: Finding[]
  briefedNotOnPage: { fact: string; note: string }[]
  openQuestions: OpenQuestion[]
  selfAssessment: { solid: string; shaky: string; mostHelpfulChange: string }
}

// ---------------------------------------------------------------------------
// Stage 2 — Drift (Phase E, written only after the human gate)
// ---------------------------------------------------------------------------

export type Grade = 'G1' | 'G2' | 'G3' | 'ungraded'

export type MismatchClass =
  | 'copy-stale'
  | 'docs-stale'
  | 'true-contradiction'
  | 'mirror-misread'
  | 'deploy-divergence'

export interface GradeRow {
  claimId: string
  grade: Grade
  notes: string
}

export interface MismatchRow {
  id: string
  mirrorRef: string
  canonSource: string
  classification: MismatchClass
  summary: string
  resolution: string
}

export interface DoorAuditRow {
  route: string
  currentDoor: { label: string; href: string } | null
  intendedDoor: string
  status: 'ok' | 'wrong-door' | 'missing-door'
  note: string
}

export interface VoiceViolation {
  route: string
  term: string
  count: number
  example: string
}

export interface DriftData {
  gradedAt: string
  grades: GradeRow[]
  mismatches: MismatchRow[]
  doorAudit: DoorAuditRow[]
  voicePass: {
    violations: VoiceViolation[]
    bannedCompetitorHits: VoiceViolation[]
    summary: string
  }
  deployDivergences: MismatchRow[]
}

// ---------------------------------------------------------------------------
// Stage 3 — Perception (Phase G, outside-in via answer engines)
// ---------------------------------------------------------------------------

export interface PerceptionRecord {
  id: string
  source: string
  query: string
  saysWeDo: string
  errors: string[]
  omissions: string[]
  quotes: string[]
}

export interface AlignmentRow {
  vertical: string
  copySays: string
  canonSays: string
  worldHears: string
  verdict: string
  likelyCause: string
}

export interface PerceptionData {
  queriedAt: string
  records: PerceptionRecord[]
  alignment: AlignmentRow[]
  fixList: { rank: number; fix: string; seededBy: string }[]
  patterns: string[]
}
